module.exports = [
    'http://tvstz.com',
    // 'http://ataka.bg',
    // 'http://wik-stz.com/bg',
    // 'http://mitropolia-starazagora.bg',
    // 'http://www.bsp-obls-starazagora.org',
    // 'http://www.nbp.bg/nbp',
    // 'http://www.presstv.bg',
    // 'http://www.beroe.bg',
    // 'https://stzagora.net',
    // 'https://trud.bg',
    // 'http://www.uni-sz.bg',
    // 'https://stz7.com',
    // 'https://www.periscop.bg',
    // 'http://zaratv.info',
    // 'http://krsz.org',
    // 'http://aes.bg',
    // 'http://www.informiran.net',
    // 'http://necbg.eu',
    // 'https://www.mdps.bg',
    // 'https://mbsp.bg',
    // // 'http://umbal-kirkovich.org',
    // 'http://www.bas.bg',
    // 'https://www.slavishow.com'
]